### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by sadeghte** [muon-protocol/muon-node-js#91]
**Describe the bug**
1: Error when trying deploy an app without specifying the list of nodes (nodes is not iterable).
2: Some nodes will error when loading one page (1500) of nodes info from contract.
3: Aggregator node not receiving tss sample app completed requests

**Comment by bakhshandeh** [comment]
> . 3: Aggregator node not receiving tss sample app completed requests

It happens because some of the monitoring nodes are not deployers and do not have access to the AppContext and can't verify the signatures here:

https://github.com/muon-protocol/muon-node-js/blob/ceee47c52dab4324d785607d6fe1620b7d68dc1d/src/network/plugins/network-ipc-handler.ts#L528-L542

The verification code is commented as a temporary workaround. The permanent solution is to make sure that all nodes can load AppContext without the party. The public key and other details of the apps should be accessible by all nodes. But `AppContext.party` is accessible only by the deployer nodes and party nodes.
